### PR TITLE
fixed wrong react native screens version

### PR DESCRIPTION
**Pull request by DennisOstertag**
Right now the sample app build is failing for ios with the error below.

```
sample/node_modules/react-native-screens/ios/RNSScreenStackHeaderConfig.m:8:9: fatal error: 'React/RCTImageLoader.h' file not found

#import <React/RCTImageLoader.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

A downgrade of the react native screens lib fixed this build error, as the sample app is build with react-native version 0.60.0.

As there were complains in the issues where the app was build without a valid ssh key, i changed pulling the lib to https.

### CODE REVIEW

**Comment by biancalui-emarsys** [comment]
Hi @DennisOstertag ,

Thanks a lot for reporting the issue and creating the pull request.
We have updated the dependencies of the sample project recently, that should resolve the issue.
I will close this PR for now.
Please feel free to create a Emarsys Zendesk ticket, and let us know if there are further questions.

Regards,
Bianca .
